laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('smarter-no-mundo', 'EmpresaController@index')->name('empresa');
    Route::get('produtos/acessorios/{acessorios_slug}', 'ProdutosController@acessorios')->name('produtos.acessorios');
    Route::get('produtos/acessorios/{acessorios_slug}/{acessorio_slug}', 'ProdutosController@acessoriosShow')->name('produtos.acessorios.show');
    Route::get('produtos/{produtos_categoria?}', 'ProdutosController@index')->name('produtos');
    Route::get('produtos/{produtos_categoria}/{produtos_slug}', 'ProdutosController@show')->name('produtos.show');
    Route::get('tutoriais/{tutoriais_categoria?}', 'TutoriaisController@index')->name('tutoriais');
    Route::get('tutoriais/{tutoriais_categoria}/{tutoriais_slug}', 'TutoriaisController@show')->name('tutoriais.show');
    Route::get('suporte', 'SuporteController@index')->name('suporte');
    Route::get('suporte/orientacoes-tecnicas', 'SuporteController@orientacoesTecnicas')->name('suporte.orientacoes-tecnicas');
    Route::post('suporte/orientacoes-tecnicas/{linha_id}/{produto_id}', 'SuporteController@orientacoesTecnicasPost')->name('suporte.orientacoes-tecnicas.post');
    Route::get('suporte/garantia-de-produtos', 'SuporteController@garantiaDeProdutos')->name('suporte.garantia-de-produtos');
    Route::post('suporte/garantia-de-produtos', 'SuporteController@garantiaDeProdutosPost')->name('suporte.garantia-de-produtos.post');
    Route::get('suporte/garantia-de-produtos/saiba-mais', 'SuporteController@garantiaDeProdutosMais')->name('suporte.garantia-de-produtos.saiba-mais');
    Route::get('suporte/manuais-de-produtos', 'SuporteController@manuaisDeProdutos')->name('suporte.manuais-de-produtos');
    Route::post('suporte/manuais-de-produtos/{produto_id}', 'SuporteController@manuaisDeProdutosPost')->name('suporte.manuais-de-produtos.post');
    Route::get('onde-comprar/{estado?}', 'OndeComprarController@index')->name('onde-comprar');
    Route::get('consultoria', 'ConsultoriaController@index')->name('consultoria');
    Route::post('consultoria', 'ConsultoriaController@post')->name('consultoria.post');
    Route::get('news', 'NewsController@index')->name('news');
    Route::get('news/novidades', 'NoticiasController@index')->name('news.noticias');
    Route::get('news/novidades/{noticias_slug}', 'NoticiasController@show')->name('news.noticias.show');
    Route::get('news/calendario-de-eventos', 'EventosController@index')->name('news.eventos');
    Route::get('news/galeria', 'GaleriaController@index')->name('news.galeria');
    Route::get('news/galeria/{galeria_slug}', 'GaleriaController@show')->name('news.galeria.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::get('busca', 'ProdutosController@busca')->name('busca');


    // Localização
    Route::get('idioma/{idioma?}', function ($idioma = 'pt') {
        if ($idioma == 'pt' || $idioma == 'en') Session::put('locale', $idioma);
        return redirect()->route('home');
    })->name('lang');


    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('setores', 'SetoresController', ['only' => ['index', 'update']]);
		Route::resource('news', 'NewsController', ['only' => ['index', 'update']]);
		Route::resource('catalogo', 'CatalogoController', ['only' => ['index', 'update']]);
		Route::resource('distribuidores', 'DistribuidoresController');
		Route::resource('ecommerces', 'EcommercesController');
		Route::resource('onde-comprar', 'OndeComprarController', ['only' => ['index', 'update']]);
		Route::resource('acessorios-consumiveis-epis/categorias', 'AcessoriosConsumiveisEpisCategoriasController', ['parameters' => ['categorias' => 'categorias_acessorios']]);
		Route::resource('acessorios-consumiveis-epis', 'AcessoriosConsumiveisEpisController');
        Route::resource('acessorios-consumiveis-epis.destaques', 'AcessoriosDestaquesController', ['parameters' => ['destaques' => 'destaques_acessorios']]);
        Route::get('acessorios-consumiveis-epis/{acessorios_consumiveis_epis}/imagens/clear', [
            'as'   => 'painel.acessorios-consumiveis-epis.imagens.clear',
            'uses' => 'AcessoriosImagensController@clear'
        ]);
        Route::resource('acessorios-consumiveis-epis.imagens', 'AcessoriosImagensController', ['parameters' => ['imagens' => 'imagens_acessorios']]);
        Route::get('consultoria/recebidos/{consultoria_recebidos}/toggle', ['as' => 'painel.consultoria.recebidos.toggle', 'uses' => 'ConsultoriaRecebidosController@toggle']);
        Route::resource('consultoria/recebidos', 'ConsultoriaRecebidosController', ['parameters' => ['recebidos' => 'consultoria_recebidos']]);
		Route::resource('consultoria', 'ConsultoriaController', ['only' => ['index', 'update']]);
        Route::resource('garantia-de-produtos', 'GarantiaDeProdutosController', ['only' => ['index', 'update']]);

        Route::get('solicitacoes-de-manuais/{solicitacoes_de_manuais}/toggle', ['as' => 'painel.solicitacoes-de-manuais.toggle', 'uses' => 'SolicitacoesManuaisController@toggle']);
        Route::resource('solicitacoes-de-manuais', 'SolicitacoesManuaisController');

        Route::get('solicitacoes-de-garantias/{solicitacoes_de_garantias}/toggle', ['as' => 'painel.solicitacoes-de-garantias.toggle', 'uses' => 'SolicitacoesGarantiasController@toggle']);
        Route::resource('solicitacoes-de-garantias', 'SolicitacoesGarantiasController');

        Route::get('solicitacoes-de-orientacoes/{solicitacoes_de_orientacoes}/toggle', ['as' => 'painel.solicitacoes-de-orientacoes.toggle', 'uses' => 'SolicitacoesOrientacoesController@toggle']);
        Route::resource('solicitacoes-de-orientacoes', 'SolicitacoesOrientacoesController');

        Route::resource('suporte', 'SuporteController', ['only' => ['index', 'update']]);
        Route::resource('produtos/linhas', 'ProdutosLinhasController', ['parameters' => ['linhas' => 'linhas_produtos']]);
        Route::resource('produtos/capas', 'ProdutoscapasController', ['only' => ['index', 'update']]);
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/{produtos}/imagens/clear', [
            'as'   => 'painel.produtos.imagens.clear',
            'uses' => 'ProdutosImagensController@clear'
        ]);
        Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'imagens_produtos']]);
        Route::get('produtos/{produtos}/fotos/clear', [
            'as'   => 'painel.produtos.fotos.clear',
            'uses' => 'ProdutosFotosController@clear'
        ]);
        Route::resource('produtos.fotos', 'ProdutosFotosController', ['parameters' => ['fotos' => 'fotos_produtos']]);
        Route::resource('produtos.videos', 'VideosController');
        Route::resource('produtos.downloads', 'DownloadsController');
        Route::resource('produtos.certificacoes', 'CertificacoesProdutosController', ['parameters' => ['certificacoes' => 'certificacoes_produtos']]);
        Route::resource('produtos.recursos-especiais', 'RecursosEspeciaisController');
        Route::resource('produtos.acessorios', 'AcessoriosController');
        Route::resource('produtos.destaques', 'DestaquesController');
        Route::resource('produtos.especificacoes-tecnicas', 'EspecificacoesTecnicasController');
        Route::resource('galerias', 'GaleriasController');
        Route::get('galerias/{galerias}/imagens/clear', [
            'as'   => 'painel.galerias.imagens.clear',
            'uses' => 'GaleriasImagensController@clear'
        ]);
        Route::resource('galerias.imagens', 'GaleriasImagensController', ['parameters' => ['imagens' => 'imagens_galerias']]);
        Route::resource('noticias', 'NoticiasController');
		Route::resource('eventos/capa', 'EventoscapaController', ['only' => ['index', 'update']]);
        Route::resource('eventos', 'EventosController');
        Route::resource('tutoriais/categorias', 'TutoriaisCategoriasController', ['parameters' => ['categorias' => 'categorias_tutoriais']]);
        Route::resource('tutoriais', 'TutoriaisController');
		Route::resource('escritorios', 'EscritoriosController');
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
		Route::resource('cabecalhos', 'CabecalhosController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
		Route::resource('chamadas', 'ChamadasController');
		Route::resource('certificacoes', 'CertificacoesController');
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');

        Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
        Route::resource('newsletter', 'NewsletterController');

        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([

laravel/app/Http/Controllers/Painel/AcessoriosConsumiveisEpisCategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AcessoriosConsumiveisEpisCategoriasRequest;
use App\Http\Controllers\Controller;

use App\Models\AcessorioConsumivelEpiCategoria;

class AcessoriosConsumiveisEpisCategoriasController extends Controller
{
    public function index()
    {
        $categorias = AcessorioConsumivelEpiCategoria::ordenados()->get();

        return view('painel.acessorios-consumiveis-epis.categorias.index', compact('categorias'));
    }

    public function create()
    {
        return view('painel.acessorios-consumiveis-epis.categorias.create');
    }

    public function store(AcessoriosConsumiveisEpisCategoriasRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = AcessorioConsumivelEpiCategoria::upload_capa();

            AcessorioConsumivelEpiCategoria::create($input);
            return redirect()->route('painel.acessorios-consumiveis-epis.categorias.index')->with('success', 'Categoria adicionada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar categoria: '.$e->getMessage()]);

        }
    }

    public function edit(AcessorioConsumivelEpiCategoria $categoria)
    {
        return view('painel.acessorios-consumiveis-epis.categorias.edit', compact('categoria'));
    }

    public function update(AcessoriosConsumiveisEpisCategoriasRequest $request, AcessorioConsumivelEpiCategoria $categoria)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = AcessorioConsumivelEpiCategoria::upload_capa();

            $categoria->update($input);
            return redirect()->route('painel.acessorios-consumiveis-epis.categorias.index')->with('success', 'Categoria alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar categoria: '.$e->getMessage()]);

        }
    }

    public function destroy(AcessorioConsumivelEpiCategoria $categoria)
    {
        try {

            $categoria->delete();
            return redirect()->route('painel.acessorios-consumiveis-epis.categorias.index')->with('success', 'Categoria excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir categoria: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/AcessoriosConsumiveisEpisController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AcessoriosConsumiveisEpisRequest;
use App\Http\Controllers\Controller;

use App\Models\AcessorioConsumivelEpi;
use App\Models\AcessorioConsumivelEpiCategoria;

class AcessoriosConsumiveisEpisController extends Controller
{
    private $categorias;

    public function __construct()
    {
        $this->categorias = AcessorioConsumivelEpiCategoria::ordenados()->lists('titulo_pt', 'id');
    }

    public function index(Request $request)
    {
        $categorias = $this->categorias;
        $filtro     = $request->query('filtro');

        if (AcessorioConsumivelEpiCategoria::find($filtro)) {
            $registros = AcessorioConsumivelEpi::where('acessorios_categoria_id', $filtro)->ordenados()->get();
        } else {
            $registros = AcessorioConsumivelEpi::leftJoin('acessorios_consumiveis_epis_categorias as cat', 'cat.id', '=', 'acessorios_categoria_id')
                ->orderBy('cat.ordem', 'ASC')
                ->orderBy('cat.id', 'DESC')
                ->select('acessorios_consumiveis_epis.*')
                ->ordenados()->get();
        }

        return view('painel.acessorios-consumiveis-epis.index', compact('categorias', 'registros', 'filtro'));
    }

    public function create()
    {
        $categorias = $this->categorias;

        return view('painel.acessorios-consumiveis-epis.create', compact('categorias'));
    }

    public function store(AcessoriosConsumiveisEpisRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = AcessorioConsumivelEpi::upload_imagem();

            AcessorioConsumivelEpi::create($input);

            return redirect()->route('painel.acessorios-consumiveis-epis.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(AcessorioConsumivelEpi $registro)
    {
        $categorias = $this->categorias;

        return view('painel.acessorios-consumiveis-epis.edit', compact('registro', 'categorias'));
    }

    public function update(AcessoriosConsumiveisEpisRequest $request, AcessorioConsumivelEpi $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = AcessorioConsumivelEpi::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.acessorios-consumiveis-epis.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(AcessorioConsumivelEpi $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.acessorios-consumiveis-epis.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CabecalhosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CabecalhosRequest;
use App\Http\Controllers\Controller;

use App\Models\Cabecalhos;

class CabecalhosController extends Controller
{
    public function index()
    {
        $registro = Cabecalhos::first();

        return view('painel.cabecalhos.edit', compact('registro'));
    }

    public function update(CabecalhosRequest $request, Cabecalhos $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['empresa'])) $input['empresa'] = Cabecalhos::upload_empresa();
            if (isset($input['tutoriais'])) $input['tutoriais'] = Cabecalhos::upload_tutoriais();
            if (isset($input['suporte'])) $input['suporte'] = Cabecalhos::upload_suporte();
            if (isset($input['onde_comprar'])) $input['onde_comprar'] = Cabecalhos::upload_onde_comprar();
            if (isset($input['consultoria'])) $input['consultoria'] = Cabecalhos::upload_consultoria();
            if (isset($input['contato'])) $input['contato'] = Cabecalhos::upload_contato();

            $registro->update($input);

            return redirect()->route('painel.cabecalhos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/solicitacoes-de-manuais/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>Solicitações de Manuais</h2>
    </legend>

    @if(!count($contatosrecebidos))
    <div class="alert alert-warning" role="alert">Nenhuma solicitação recebida.</div>
    @else
    <table class="table table-striped table-bordered table-hover data-table">
        <thead>
            <tr>
                <th>Data</th>
                <th>Nome</th>
                <th>E-mail</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($contatosrecebidos as $contato)

            <tr class="tr-row @if(!$contato->lido) warning @endif">
                <td data-order="{{ $contato->created_at_order }}">{{ $contato->created_at }}</td>
                <td>{{ $contato->nome }}</td>
                <td>
                    <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $contato->email }}" style="margin-right:5px;border:0;transition:background .3s">
                        <span class="glyphicon glyphicon-copy"></span>
                    </button>
                    {{ $contato->email }}
                </td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.solicitacoes-de-manuais.destroy', $contato->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.solicitacoes-de-manuais.show', $contato->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-align-left" style="margin-right:10px;"></span>Ler mensagem
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>

                        <a href="{{ route('painel.solicitacoes-de-manuais.toggle', $contato->id) }}" class="btn btn-sm pull-left {{ ($contato->lido ? 'btn-warning' : 'btn-success') }}">
                            <span class="glyphicon small {{ ($contato->lido ? 'glyphicon-repeat' : 'glyphicon-ok') }}"></span>
                        </a>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>

        @endforeach
        </tbody>
    </table>
    @endif

@stop

laravel/resources/views/painel/solicitacoes-de-manuais/show.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2>Solicitações de Manuais</h2>
    </legend>

    <div class="form-group">
        <label>Data</label>
        <div class="well">{{ $contato->created_at }}</div>
    </div>

    <div class="form-group">
        <label>Nome</label>
        <div class="well">{{ $contato->nome }}</div>
    </div>

@if($contato->cpf_cnpj)
    <div class="form-group">
        <label>CPF / CNPJ</label>
        <div class="well">{{ $contato->cpf_cnpj }}</div>
    </div>
@endif

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>E-mail</label>
                <div class="well">
                    <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $contato->email }}" style="margin-right:5px;border:0;transition:background .3s">
                        <span class="glyphicon glyphicon-copy"></span>
                    </button>
                    {{ $contato->email }}
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>Telefone</label>
                <div class="well">{{ $contato->telefone }}</div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label>Produto</label>
        <div class="well">{{ $contato->produto }}</div>
    </div>

@if($contato->nf)
    <div class="form-group">
        <label>Cópia da nota fiscal</label>
        <div class="well">
            <a href="{{ url('arquivos/'.$contato->nf) }}" target="_blank">{{ $contato->nf }}</a>
        </div>
    </div>
@endif

    <a href="{{ route('painel.solicitacoes-de-manuais.index') }}" class="btn btn-default btn-voltar">Voltar</a>

@stop